name: resource_quotable

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    platform: linux/arm64/v8
    volumes:
      - ..:/workspaces/resource_quotable:cached
    ports:
      - "3000:3000"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      - RAILS_ENV=development
      - DOCKER_ENVIRONMENT=true
